version: "3.3"
services:
  web:
    build: frontend/
    ports:
      - "8910:80"
    links:
      - server

  redis:
    image: redis:latest

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: software-theory
      MYSQL_ROOT_PASSWORD: zyven
    volumes:
      - /data/software-theory/mysql:/var/lib/mysql

  server:
    build: .
    ports:
      - "10000:8080"
    restart: always
    links:
      - "redis:redis"
      - "mysql:mysql"
    depends_on:
      - "redis"
      - "mysql"
    volumes:
      - /data/software-theory/config:/app/config
